import type { Metadata } from "next";
import {
  DynaPuff,
  Overpass,
  Radio_Canada,
  Gideon_Roman,
} from "next/font/google";
import "../styles/globals.css";
import QueryProvider from "@/components/providers/query-provider";
import { GameProvider } from "@/components/providers/game-provider";
import NextTopLoader from "nextjs-toploader";

const dynaPuff = DynaPuff({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-dynaPuff",
});
const overpass = Overpass({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-overpass",
});
const canada = Radio_Canada({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-canada",
});
const gideon = Gideon_Roman({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-gideon",
  weight: "400",
});

// #TODO add splash screen. idea was side by side by side arrow ⬆️⬇️ from out screen to center to out.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dynaPuff.variable} ${overpass.variable} ${canada.className} ${gideon.variable} overflow-hidden relative bg-slate-800`}
      >
        <NextTopLoader
          showSpinner={false}
          initialPosition={0.3}
          speed={1000}
          height={4}
          color="#fece3f"
        />
        <QueryProvider>
          <GameProvider>{children}</GameProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
