import type { Metadata } from "next";
import { Inter, DynaPuff, Overpass, Radio_Canada } from "next/font/google";
import "../styles/globals.css";
import QueryProvider from "@/components/providers/query-provider";
import { GameProvider } from "@/components/providers/game-provider";

const dynaPuff = DynaPuff({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-dynaPuff",
});
const overpass = Overpass({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-overpass",
});
const canada = Radio_Canada({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-canada",
});

// #TODO PRIO add splash screen. idea was side by side by side arrow ⬆️⬇️ from out screen to center to out.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dynaPuff.variable} ${overpass.variable} ${canada.className} overflow-hidden relative bg-slate-800`}
      >
        <QueryProvider>
          <GameProvider>{children}</GameProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
